/**
 * 山西-晋中市-美食
 * 介休贯馅糖,猫耳朵,荞面凉粉,平遥碗托,灌馅糖,太谷饼,平遥牛肉,吊炉烧饼,珍珠粥,寿阳茶食,扁食头脑,
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const jinzhongFoodsList = [
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '介休贯馅糖',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '猫耳朵',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '荞面凉粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '平遥碗托',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '灌馅糖',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '太谷饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '平遥牛肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '吊炉烧饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '珍珠粥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '寿阳茶食',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '山西',
    city: '晋中市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '扁食头脑',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jinCuisine',
    cuisineCategoryName: '晋菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
