/**
 * 广东省-云浮市-美食
 * 罗定豆豉鸡,慈姑糍,新兴裹蒸粽,茶洞豆腐,大糠糍,泗纶蒸笼,罗定皱纱鱼腐,
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const yunfuFoodsList = [
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '罗定豆豉鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '慈姑糍',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '新兴裹蒸粽',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '茶洞豆腐',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '大糠糍',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '泗纶蒸笼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '云浮市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '罗定皱纱鱼腐',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
