/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-10-20 19:04:17
 * @FilePath: /cooking-menu/src/views/asia/eastAsia/china/mockData/hunanProvince/yongzhou.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 湖南-永州市-美食
 * 永州血鸭,柚皮红烧肉,什锦火锅,道州喝螺
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const yongzhouFoodsList = [
  // 永州血鸭是湖南省永州市的一道特色名菜，属于湘菜系；永州血鸭分为多种，有江永，道县，新田、宁远、蓝山、东安、双牌等多个说法，在当地，几乎家家户户都会制作此菜，其具有美味、开胃凉血的特点，
  {
    province: '湖南省',
    city: '永州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '永州血鸭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '永州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '柚皮红烧肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 什锦火锅是一道色香味俱全的名肴，属于津菜系冬令时菜。火锅食材包括各种肉类、海鲜类、蔬菜类、豆制品类、菌菇类、蛋类制品,将其放入煮开的清水或特制的高汤锅底烫熟后食用。有些吃法还会蘸上调味料 一起食用。由于食材、配料、使用方法丰富多彩，故名“什锦火锅”。老少咸宜，至冬之佳品。什锦火锅选料精细、品种多样、色彩缤纷、汤鲜味醇、营养丰富，是家宴不可缺少的一道佳肴。其中大同、上海的“什锦火锅”尤为出名。
  {
    province: '湖南省',
    city: '永州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '什锦火锅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 道州喝螺是选用本地所产铁螺加工烹调而成，具有哺香脆嫩、汤鲜味美等特点，带有浓厚的地方风味。
  {
    province: '湖南省',
    city: '永州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '道州喝螺',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
