/**
 * 湖南-株洲市-美食
 * 醴陵炒粉,攸县米粉,小炒肉
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const zhuzhouFoodsList = [
  // 醴陵炒粉是一道美味可口的传统小吃，属于湘菜系醴陵菜。作为醴陵最负盛名的菜品，极似电影《食神》中的蛋炒饭，食材简单，做法也不复杂，但味道全系于掌勺人对火候的精准把握，是油与火的艺术。醴陵炒粉既是醴陵厨艺人高超的烹饪技术的代表，也是醴陵人巧手办事、化平淡为神奇的精明特质的体现。醴陵炒粉是街边早餐和夜宵的绝对主角，醴陵炒粉的独特味道更是醴陵游子无法在他乡尝到的家乡的味道，足令他们魂牵梦绕。
  {
    province: '湖南省',
    city: '株洲市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '醴陵炒粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 攸县米粉，是湖南省株洲市攸县的一种地方特色米粉，是国家地理标志保护产品，其口感细腻，爽嫩。跟其它的米粉制作方法大致相同，主要以大米为原料，经浸泡、蒸煮、压条等工序制成的细小的条状，其质地柔韧，富有弹性，水煮不糊汤，干炒不易断，配以各种菜码或汤料进行汤煮或干炒，爽滑入味，深受广大老百姓的喜爱。
  {
    province: '湖南省',
    city: '株洲市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '攸县米粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 小炒肉是湖南省一道常见的特色传统名菜，属于湘菜系。麻辣鲜香，口味滑嫩。制作原料主要是五花肉和青椒、红椒等。
  {
    province: '湖南省',
    city: '株洲市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '小炒肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hunanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
