/**
 * 甘肃-嘉峪关市-美食
* 搓鱼子,嘉峪关机面,糖油糕,羊肉垫卷子,糖耳朵,扣肘子,酿皮子,甜醅子,驴肉黄面,嘉峪关烤羊肉,,


 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const jiayuguanFoodsList = [
  // 1.搓鱼子,搓鱼子是嘉峪关市的一道传统特色美食，历史悠久。它的制作工艺独特，将细长的面条搓成鱼儿的形状，再配以精心调配的调料，入口爽滑，味道鲜美，是当地人民喜爱的美食。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '搓鱼子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 2.嘉峪关机面,嘉峪关机面是嘉峪关市的又一道特色美食，以其独特的制作工艺和口感著称。面皮经过多道工序精心制作，呈现出细腻的纹理，再配以鲜美的羊肉和独特的调料，味道浓郁，口感丰富。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '嘉峪关机面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 3.糖油糕,糖油糕是嘉峪关市的一种传统甜品，外皮酥脆，内馅香甜。制作时将糯米粉与糖、油充分混合，制成薄薄的外皮，再包入丰富的馅料，口感层次丰富，甜而不腻。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖油糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 4.羊肉垫卷子,羊肉垫卷子是嘉峪关市的一道特色美食，将羊肉与面粉、蔬菜等食材混合烹制，口感鲜美。制作时将羊肉切成薄片，与蔬菜、调料等混合，再用面粉制成卷子状，蒸煮而成。入口肉质鲜嫩，味道浓郁。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '羊肉垫卷子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 5.糖耳朵,糖耳朵是嘉峪关市的一道传统小吃，形状似耳朵，口感酥脆，味道香甜。制作时将面粉与糖、油等混合，制成耳朵形状，再经过炸制而成。入口酥脆，甜度适中。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖耳朵',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 6.扣肘子,扣肘子是嘉峪关市的一道传统美食，以其色香味俱佳而备受推崇。制作时将猪肉经过多道工序精心烹制，再配以当地独特的调料，入口即化，味道鲜美。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '扣肘子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 7.酿皮子,酿皮子是嘉峪关市的一道传统小吃，以其滑嫩爽口而备受喜爱。制作时将面粉制成薄薄的皮子，再配以鲜美的羊肉和独特的调料，入口滑嫩，味道鲜美。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '酿皮子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 8.甜醅子,甜醅子是嘉峪关市的一种传统饮品，以其清凉解暑、口感香甜而备受推崇。制作时将大麦、小麦等粮食发酵而成，口感醇厚，香甜可口。是夏季消暑的好选择。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '甜醅子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 9.驴肉黄面,驴肉黄面是嘉峪关市的一道特色美食，以驴肉和黄面为主要食材，口感鲜美。制作时将驴肉切成薄片，与蔬菜、调料等混合，再用黄面制成条状，蒸煮而成。入口肉质鲜嫩，面条Q弹有劲。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '驴肉黄面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 10.嘉峪关烤羊肉,嘉峪关烤羊肉是嘉峪关市的一道传统美食，以其独特的制作工艺和口感著称。制作时将羊肉切成小块，用特制的烤架烤制而成。入口羊肉外酥里嫩，味道鲜美。
  {
    province: '甘肃省',
    city: '嘉峪关市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '嘉峪关烤羊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
