/**
 * 甘肃-兰州市-美食
 * 高三酱肉,兰州拉面,猪脏面,陈春麻辣粉,油炒粉,兰州臊子面,黄焖羊肉,兰州牛肉面,百花全鸡,浆水面
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const lanzhouFoodsList = [
  // 高三酱肉是甘肃兰州的传统名食，属于甘肃菜。此菜肉质新鲜、色泽光亮，略显透明，不肥不腻，芳香四溢而闻名遐迩。是由高彬吾在集各地传统酱肉制作技艺精华的基础上，精心研究，卤制而成。因高氏行三而得名，已有近70年的历史，现主要在张掖路西端的福华轩专门经营。
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '高三酱肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 兰州牛肉拉面，是甘肃省兰州市的特色美食，是一种食品名称，原名兰州牛肉面，始于清朝嘉庆年间（1799年），系东乡族马六七从河南省怀庆府清化陈维精处学成带入兰州的，后经后人陈和声、马宝仔等人以“一清（汤）二白（萝卜）三绿（香菜蒜苗）四红（辣子） 五黄（面条黄亮）”统一了兰州牛肉面的标准。在其后二百多年的漫长岁月里，以一碗面而享誉天下，以肉烂汤鲜、面质精细而蜚声中外，青海人将兰州牛肉面以兰州拉面的商标打入了全国各地，赢得了国内乃至全世界范围内食客的好评和荣誉。1999年，兰州拉面被国家确定为中式三大快餐试点推广品种之一。
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '兰州拉面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 猪脏面是一到用猪大肠烹制的传统名吃，属于甘肃菜。清代兰州人创制，民国时以宣家巷的风味最佳。因制作精巧、软烂醉香、风味独特而颇受欢迎。
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '猪脏面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 陈春麻辣粉是现定居兰州的川味“麻辣陈”传人陈德金1989年来兰后，在传统配方的基础上，结合当地口味，创出的一个最受欢迎的川味小吃。现集众多川味、名优小吃和火锅系列于一体的大型饮食基地“陈春楼”在工贸商场后院已正式开业。陈春麻辣粉已在市区繁华地带设有4个连锁店，除工贸商场后院有两家外，另两家设在西口食品一条街和农民巷。
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '陈春麻辣粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 油炒粉也是一道甘肃兰州市著名的特色传统小吃。有卖酿皮的地方一般都卖油炒粉。油炒 粉为用卤猪油炒制的凉粉。先在乎底铁锅内烧开卤猪油，再把切成麻将牌大的方块粉分次放入锅内，加糖色、葱花、精盐，
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油炒粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 兰州臊子面是以面粉为原料制作的一道菜品，是兰州市著名的传统面食。
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '兰州臊子面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 黄焖羊肉，是西北经典的名菜之一。此菜口味香酥， 肥而不腻。其是清朝末代皇帝的御膳菜肴。羊肉富有营养，具有暖中补气、滋养、御风寒、生肌健力等功效
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '黄焖羊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '兰州牛肉面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '百花全鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '甘肃省',
    city: '酒泉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '浆水面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
