/**
 * 湖南小吃
 * 新饭、脑髓卷、米粉、八宝龟羊汤、火宫殿臭豆腐、糯米粽子、麻仁奶糖、浏阳茴饼、浏阳豆豉、芙蓉三鲜火锅、湘宾春卷、
 * 年糕、馓子、龙脂猪血、口味虾、结麻花、姊妹团子、萝卜丝饼、薯丁粑粑、糖油粑粑等。
 * 长沙小吃
 * 姜二爹的臭豆腐，张桂生的馓子，李子泉的神仙钵饭，胡桂英的猪血，邓春香的红烧蹄花，
 * 罗三的米粉及三角豆腐、牛角蒸饺等，共 300 余个品种。2013 年，火宫殿小吃在继承传统的基础上，开发新品，形成系列。
 * 主要品种有糯米粽子、麻仁奶糖、浏阳茴饼、浏阳豆豉、湘宾春卷等。
 */
// import { lampshadedBeefScriptsList } from './huNanFoodScriptContent/lampshadedBeef';
export const huNanSnacksFoodsList = [
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '脑髓卷',
    foodName_en: 'medullaOblongata',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '火宫殿臭豆腐',
    foodName_en: 'stinkyTofu',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '芙蓉三鲜火锅',
    foodName_en: 'hibiscusSanshoHotPot',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '湖南馓子',
    foodName_en: 'deepFriedNoodleCake',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  // 口味虾，又名麻辣小龙虾、长沙口味虾、香辣小龙虾,是湖南省的一道传统名菜，属于湘菜系，该菜品以小龙虾制成，口味麻辣鲜香，色泽红亮，质地滑嫩，滋味香辣。20世纪末开始传遍全国，成为人们夏夜街边啤酒摊的经典小吃。主料所用龙虾原产自北美洲，1918年由美国引入日本，1929年再由日本引入中国，生长在中国南方的河湖池沼中。
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '口味虾',
    foodName_en: 'flavoredShrimp',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '结麻花',
    foodName_en: 'twist',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '姊妹团子',
    foodName_en: 'sisterDoughnut',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '臭豆腐',
    foodName_en: 'stinkyTofu',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '猪血',
    foodName_en: 'pigBlood',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '红烧蹄花',
    foodName_en: 'braisedHoofMeat',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '三角豆腐',
    foodName_en: 'triangularShapedTofu',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
  },
  // 长沙臭豆腐是湖南省长沙市的一道传统特色小吃，属于湘菜。长沙臭豆腐以臭豆腐等食材用料烹制，其色墨黑，外焦里嫩，鲜而香辣， 焦脆而不糊、细嫩而不腻、初闻臭气扑鼻，细嗅浓香诱人。2021年6月，火宫殿臭豆腐制作技艺入选国家级非遗名录。
  // 火宫殿臭豆腐是湖南省长沙市的一道传统名小吃，该菜品属于湘菜系；此菜用黄豆为原料的水豆腐，经过专用卤水浸泡半月，再以茶油经文火炸焦，佐以麻油，辣酱。它具有"黑如墨，香如醇，嫩如酥，软如绒"的特点，奇在以臭命名，不同于其它食卤以香自翊。闻起来臭，吃起来香，外焦微脆，内软味鲜。这是因为卤水中放有鲜冬笋、浏阳豆豉、香菇、上等白酒等多种上乘原料，故味道特别鲜香。
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '长沙臭豆腐',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 湘宾春卷，是湖南长沙地区特色传统小吃。其特点是香脆、绵软、多汁、鲜嫩。馅料可根据食客的口味更换。
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '湘宾春卷',
    foodName_en: 'xiangbinSpringRolls',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 椒盐馓子，流行于中国湖南省长沙市，是一道传统小吃，其丝条粗细均匀、质地焦脆酥化、口味有甜有咸，老少皆宜，其造型新颖别致，既可当点心，亦可菜食。
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '椒盐馓子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 平江酱干是一道美味可口的传统小吃，属于湘菜系。起源于湘鄂赣边塞重镇岳阳市平江县长寿街，又名长寿酱干，是清咸丰年间百岁老人何维丰（1847—1947）首创。采用长寿街传统卤制与烘烤食品工艺相结合手法，烧制出具有方寸大小、铜钱厚薄、乌黑油亮、芳香四溢的豆腐干，取名“多珍酱干”。每十片用棉线一匝，谓之一筒。味道醇美，耐嚼爽口，到民国年间，长寿酱干已是香遍湘鄂赣边区，成了平江的一大特产。
  {
    province: '湖南省',
    city: '岳阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '平江酱干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '猪血团子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '雪花团子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '平江香干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '豆腐干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '武冈米花',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '炸八块',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '辣条',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '长沙麻仁',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '雕花蜜饯',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '湖南马打滚',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '湖北鸭脖子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '长沙市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '靖港香干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖南省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '湘黄鸡臭豆腐',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'huNanCuisine',
    cuisineCategoryName: '湘菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
console.log('湖南小吃:', huNanSnacksFoodsList, huNanSnacksFoodsList.length);
