/**
 * 河北-廊坊市-美食
 *
 * 香河肉饼,大城驴肉,薛家窝头,永清胡记烧鸡,清真八大碗
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const langfangFoodsList = [
  // 香河肉饼是河北省廊坊市香河县特产。特点是皮薄，肉厚，油香，吃起来面质软和，肉鲜细嫩，符合北方人的吃喝习惯，既可当菜，也可做主食。有两百多年的历史了。
  {
    province: '河北省',
    city: '廊坊市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '香河肉饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 大城驴肉是河北大城县汉族传统名吃，属于地方特产。俗称“天上龙肉、地下驴肉”。大城驴肉源于晚清，祖传方法制作，配料讲究，风味独特，有清香怡人，美而不腻之感，是大城饮食“三宝”之一。清朝总管太监李莲英（大城籍）曾将大城驴肉献予慈禧太后，得誉“地上珍品”之称，从此大城驴肉名声大振。改革开放以来，大城驴肉得以开发，采用传统加工制作方法，经高温消毒，真空包装后行销全国。
  {
    province: '河北省',
    city: '廊坊市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '大城驴肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 百年传统、宫廷贡品―里坦薛家窝头。清朝道光年间，直隶省顺天府大城县里坦（古）镇，薛氏独辟蹊径，制做窝头。
  {
    province: '河北省',
    city: '廊坊市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '薛家窝头',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 永清胡记烧鸡是一道色香味俱全的名小吃。始于清末，早于北京经营，已有100多年历史，亲传四代，奉承独家中药秘方薰煮，煮至骨，肉相离而形不散之细处，有口味香润、松嫩、细腻之特点。
  {
    province: '河北省',
    city: '廊坊市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '永清胡记烧鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 清真八大碗系穆斯林传统的民间宴客形式，指的是八种装在大碗里的炖菜，讲究料厚物重、味纯汤清、用料广泛、技法全面、有素有荤，牛羊肉、鸡、鸭、鱼都入八大碗之列，多采用炖、煮、烩、炸、烧、蒸等
  {
    province: '河北省',
    city: '廊坊市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清真八大碗',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
