/**
 * 云南-保山市-美食
 * 头脑锅子,永昌板鸭施甸三味,菜花腌菜伴蜂仔,油炸撒撇五滴水,口水羹施甸豆片,春甜黄酒,饵丝透心绿,保山大烧,大救驾,腌菜膏,山林素席,下村豆粉,腾冲果脯,坛子鸡,干腌菜,蒲缥甘蔗,腾冲大救驾（炒饵块）,腾冲饵丝,保山绿豆,卷粉
 */
// 蘸水兔
// 做法：

// 1、宰杀治净的带皮兔5只（每只净重约1200克）放入细流水下冲洗3小时至兔肉颜色白净，下入冷水锅中，加入姜块、花椒，中火煮20分钟，离火后再焖至自然冷却，以便兔肉吸水变嫩。
// 2、将兔子捞起沥水，拆去骨头，改刀成1.5厘米见方的块备用。

// 3、取兔丁300克装盘，带蘸水上桌。

// 蘸水制作：

// 味精3克、花椒面3克、酱油4克、保宁醋5克、姜汁5克、葱花6克、盐8克、蒜泥8克、小米辣碎20克、矿泉水50克调成蘸水。

// 蘸水翡翠玉兔

// 原料：

// 带皮仔兔200克，冰鲜蚕豆瓣100克，鲜小米椒末8克，蒜末5克、姜片、葱节、葱花各少许。

// 调料：

// 美极鲜15毫升，鲜辣汁10毫升，盐、白酒、白醋各适量。

// 做法：

// 1、把带皮仔兔放沸水锅里，加姜片、葱节、白酒、白醋和少许的盐，文火煮8分钟后，关火浸泡2小时至熟，捞出待用。

// 2、将蚕豆瓣下锅煮熟，捞出来捣成泥，待用。

// 3、将仔兔拆去骨，铺上蚕豆泥再卷成椭圆形的卷，然后裹上保鲜膜使之定型。临出菜时，取出来切成片装盘，随配蘸水碟上桌。

// 鲜辣味蘸水：

// 去鲜小米椒末、蒜末、美极鲜、鲜辣汁和葱花，调匀即成。

// 傣味米粉鱼生

// 主料：

// 米粉300克，虹鳟鱼100克。

// 辅料：

// 大蒜30克，香菜10克，韭菜30克，香柳20克，金芥10克，缅甸香菜20克，小米辣30克。

// 调料：

// 柠檬汁2克，盐3克，糖2克。

// 制作：

// 1、300克米粉用清水略煮2分钟，捞起过凉，晾干水汽，用筷子将米粉卷成30克一个的卷状摆盘。

// 2、将100克虹鳟鱼去皮，切成宽2厘米、长4厘米、厚0.5厘米的片状，放在米粉上面，随柠檬撒上桌即可。

// 柠檬撒调制：

// 将辅料全部切成细末，加入柠檬汁、盐、糖、和适量矿泉水搅拌均匀成蘸料，用来调味米粉和鱼肉，即成。

// 这道柠檬撒没有放入荤食，纯粹的植物香气不会过分抢夺鱼生的鲜美。

// 酸菜蹄花

// 制作：

// 1、选用上好的猪蹄，将其表皮用燎火烧尽余毛，至皮焦黄，浸泡后刮净焦皮，并砍成大块，入沸水锅中加料酒汆透后捞出，接着用清水冲净。

// 2、再放入炖锅内，加清水、姜块、香葱结，炖3小时直至皮糯酥软而不烂，肉嫩化渣不腻时，捞出待用；自制酸菜切成节；西红柿切成半月片。

// 3、炒锅置旺火上，放入适量的熟猪油烧热，下入姜片、酸菜节煸炒至出香。

// 4、掺入猪蹄鲜汤，放入炖好的猪蹄花，加精盐、鸡精、胡椒面略煮片刻后，起锅倒入火锅盆内，撒上西红柿片、葱节即成，配以蘸水即可上桌。

// 蘸水调制：

// 取一个小碗（按人数每份计），放入蒜米、煳辣椒面、侧耳根粒、精盐、花椒面、酱油和葱花配制成蘸水，加一点原汤蘸食即可。

// 当然，你如果以为这些就是云南蘸水的全部，那真的太小瞧云南人的创意了。据说一个合格的云南人，至少能口述十五种、动手做出五种不同的蘸水。

// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const baoshanFoodsList = [
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '头脑锅子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '永昌板鸭施甸三味',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '菜花腌菜伴蜂仔',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油炸撒撇五滴水',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '口水羹施甸豆片',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '饵丝透心绿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '保山大烧',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '腌菜膏',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '山林素席',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '坛子鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '干腌菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蒲缥甘蔗',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '腾冲大救驾（炒饵块）',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '腾冲饵丝',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '保山绿豆',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
