/**
 * 内蒙古自治区-包头市-美食
 * 小肥羊火锅,莜面,稍美,手扒肉,铁锅焖面,羊杂碎,烤全羊
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const baotouFoodsList = [
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '莜面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // （音shāomài，与南方烧麦不同）：该食品历史悠久。选用锡林郭勒草原鲜羊肉做馅，配以大葱，优质河套面粉做皮精制而成，上屉蒸熟即可。成品呈石榴状，可做宴席中的点心，又是民间美餐。德兴源稍美以皮薄、馅嫩、味香、形美著称，在稍美经营中独占鳌头。
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '稍美shāomài',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 手扒肉是红食中的一种。蒙古族人民称肉食为红食，蒙语叫“乌兰伊德”。顾名思义，“手扒肉”就是手抓羊肉，是蒙古族千百年来的传统食品，是牧民们的家常便饭。
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '手扒肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 是基于铁锅烩菜的基础上的一道类似农家饭一样的美食，是西北人民对美食研究制作出的精品。
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '铁锅焖面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 羊杂碎集羊内脏于一锅，形色繁多，肉质各异，味道酸辣兼宜，无腥不腻，汤鲜味美，入口生津，营养丰富，在气候偏冷的北方食用可御冷逐寒。
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '羊杂碎',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 蒙古族传统名菜，为招待贵宾或举行重大庆典时的盛宴特制的佳肴。一般选用草原上膘肥、体重40斤左右的绵羊宰杀后，去毛带皮腹内加葱、姜、椒、盐等佐料整体烤制而成。烤完以后，羊形完整，羊跪在方木盘内，色泽金红，羊皮酥脆，羊肉嫩香。
  {
    province: '内蒙古自治区',
    city: '包头市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '烤全羊',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
