/**
 * 内蒙古自治区-兴安盟市-美食
 * 锅包肉,小鸡炖蘑菇,烤全羊
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const xingAnMengFoodsList = [
  // 锅包肉（英文名：Fried Pork in Scoop），原名锅爆肉，光绪年间始创自哈尔滨道台府府尹杜学瀛厨师郑兴文之手。成菜后，色泽金黄，口味酸甜。锅包肉是为适应外宾口味，把咸鲜口味的“焦烧肉条”改成了一道酸甜口味的菜肴。通常将猪里脊肉切片腌入味，裹上炸浆，下锅炸至金黄色捞起，再下锅拌炒勾芡即成。2022年，哈尔滨锅包肉入选国家《地标美食名录》。
  {
    province: '内蒙古自治区',
    city: '兴安盟',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '锅包肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 蒙古族传统名菜，为招待贵宾或举行重大庆典时的盛宴特制的佳肴。一般选用草原上膘肥、体重40斤左右的绵羊宰杀后，去毛带皮腹内加葱、姜、椒、盐等佐料整体烤制而成。烤完以后，羊形完整，羊跪在方木盘内，色泽金红，羊皮酥脆，羊肉嫩香。
  // 烤全羊（Roast Whole Lamb），是一道地方特色菜肴。色、香、味、形俱全，别有风味。
  {
    province: '内蒙古自治区',
    city: '兴安盟',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '烤全羊',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
