/**
 * 河南-安阳市-美食
 * 
老庙牛肉,安阳三熏,
道口烧鸡,扣碗酥肉,
秦氏熏肉,八宝布袋鱼,
万古羊肉卤,
皮渣,
*/
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const anyangFoodsList = [
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '老庙牛肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '安阳三熏',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 道口烧鸡是河南省安阳市的特色传统名菜之一，被誉为中华第一鸡。该菜品由安阳市滑县道口镇“义兴张”世家烧鸡店所制，是我国著名的特产。 道口烧鸡与北京烤鸭齐名。用多种名贵中药，辅之陈年老汤，其成品烧鸡色泽鲜艳，形如元宝，口衔瑞蚨。极具食疗和保健功能。创业于清朝顺治十八年（1661年），已有三百多年的历史，开始制作不得法，生意并不兴隆，后从清宫御膳房的御厨那里求得制作烧鸡秘方，做出的鸡十分香美。道口烧鸡的制作技艺历代相传，形成自己的独特风格。1981年被商业部评为全国名特优产品。豫北滑县道口镇，素有"烧鸡之乡"的称号。"义兴张"的道口烧鸡，像北京烤鸭一样，在全国食品中独占鳌头，并且誉满神州，名扬海外。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '道口烧鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 扣碗酥肉是一道河南安阳的名菜，属于豫菜，是安阳当地饮食的代表菜品，其特点是香酥、嫩滑、爽口、肥而不腻，选用猪上身精肉，肥瘦相间。扣碗酥肉的做法历史悠久，以五花肉为主要材料，烹饪的做法蒸菜为主，口味属于咸鲜，口味偏淡。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '扣碗酥肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 秦氏熏肉是一道色香味俱全的名肴，属于豫菜系。说起熏肉，古已有之，纵观中国古代饮食，早在唐代以前，“炙品”就在菜肴中占有很大的比重。但值得一提的是安阳地方特色“三熏”的代表作之一“秦氏熏肉”。据传清高宗乾隆十五年（1750年）间，乾隆皇帝巡幸河南嵩山，途经安阳小憩，进膳时对当地官员进奉的一道菜“熏肉”赞不绝口。至此“秦氏熏肉”在民间广为传扬。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '秦氏熏肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 八宝布袋鱼，是以鲤鱼、姜醋汁为原料制作的一道菜品，属于豫菜系。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '八宝布袋鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 万古羊肉卤，是以羊肉、醋液、大料等为原料制作的一道菜品。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '万古羊肉卤',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 皮渣又称“渣”是发源于河南安阳和河北邯郸的一种特色地方菜，河南安阳、冀西南以及周边各县市的婚宴三下锅文化、三道饭文化、八大碗菜系均使用皮渣作为主要食材，是独具地方特色菜肴。此菜可煎可烩，炒菜做汤，味美可口，别有风味。口感筋道、香而不腻、后味绵长。作为淀粉的再加工副食，在粉条的加工过程中配调味料后盛如模具定形而成，也有用粉条进行二次煮食后加入海米，葱花、蒜片、姜末、酱油,加水搅拌蒸制而成。
  // 安阳皮渣是河南省传统的地方名菜，属于豫菜系。安阳“三大宝”之一。成品其色微碧，呈半透明状，触之柔软而有弹性，闻之浓香扑鼻，口感爽滑、筋道。主要以粉条为主，加上大葱、大蒜、荤油、精盐、香油、虾皮、红薯淀粉、猪油、姜末等制作而成。
  {
    province: '河南省',
    city: '安阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '皮渣',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
