/**
 * 河南-郑州市-美食
 * 郑州烩面,郑州蒸饺,郑州焖饼,郑州黄河鲤鱼焙面,葛记焖饼,少林寺素饼,龙须糕,琵琶酥,御饼,丁家粉蒸肉,胡辣汤,油馍头,月亮馍,肉盒
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const zhengzhouFoodsList = [
  // 郑州烩面选用上好的鲜羊肉，羊骨，经浸泡，用大火将骨头和肉一起煮成白汤，另用面粉，和成软面，经反复揉搓，用手工拉成宽窄不同、粗细不等的条状下锅，锅内放原汤，放上羊肉，配上黄花菜、木耳、粉条，用餐时，配上香菜、辣椒油、糖蒜等小碟，味道更鲜。 [301]
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '郑州烩面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 郑州蒸饺制作讲究，肉馅须用肥肉三成、瘦肉七成，加入姜米、料酒、小磨油、精盐、味精、水等搅拌上劲成汤馅。蒸饺皮采用烫面、死面混合而成，反复揉搓后方能使用。包蒸饺更有讲究，每个蒸饺必须12-13褶，多褶少褶即视为废品。所以，蒸饺成品具有造型美观、色泽油亮、灌汤流油等特点。 [299]
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '郑州蒸饺',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 郑州焖饼的制作工序是精选五花猪肉，切成两公分见方的肉丁，配八大料入坛，温火慢炖；然后和面、烙饼，切成饼条，然后配菜，放入铁炒锅焖制。 [300]
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '郑州焖饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 郑州黄河鲤鱼焙面选用黄河生态大鲤鱼，经除腥源、鱼体按摩、刀解鱼肉、宽油浸炸，使用高汤提鲜；“龙须面”过油炸焦，使其蓬松酥脆，吸汤汁后，配菜肴同食。 [302]
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '郑州黄河鲤鱼焙面',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 葛记焖饼是河南省郑州市的特色小吃之一，也是“京都老号”葛记坛子肉焖饼馆独家经营的一种传统特色小吃。焖饼时，锅内用青菜铺底，放上饼条和坛子肉，加高汤稍焖即成。其肉香醇厚，肥而不腻，其饼柔软适口，老少皆宜。焖饼时配菜除用豆芽外，更多是用四季鲜菜，如蒜苔、小白菜、四季梅、茭白等。焖饼用的汤，除猪肉汤外，还用鸡汤、鸭骨汤，因此焖出的饼软香不腻，鲜美爽口。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '葛记焖饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 少林寺素饼的配方很讲究，所用原料酥油是全素食酥油。素饼含低糖，不含脂肪，口感香酥浓郁。所用原料酥油是台湾产的纯素酥油。素饼低糖，不含脂肪，食后有迅速补充体能之功效。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '少林寺素饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 龙须糕是河南省郑州市的一种传统特色糕点，属于河南小吃。哪吒闹海的神话故事，在中国家喻户晓，小哪吒骑在老龙王的背上，剥了它的皮，抽了它的筋，最后把龙须也割了，交给厨师，做成食品，分给百姓们吃了，这食品，就是流传的龙须糕。其特点是口感香酥，味道甜咸。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '龙须糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 琵琶酥是由乾隆期间发起的一种酥皮无馅点心。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '琵琶酥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 御饼即茯苓夹饼。相传是赵匡胤当皇帝那天，赐给文武大臣的点心，故而得名。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '御饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 丁家粉蒸肉是一道河南省郑州市新郑市的传统名菜，属于豫菜系。此菜红光透亮，样如水晶，香气扑鼻，诱人食欲。蒸肉始自清末丁家饭庄，距今有一百二十年历史，曾经皇帝御厨指点，会南北风味精华，在传统基础上创造的一道名菜。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '丁家粉蒸肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 胡辣汤，是河南早餐中常见的传统汤类名吃，用胡椒、辣椒、草果、牛肉粒、骨汤、粉芡、细粉条、黄花菜、花生、木耳等制作而成。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '胡辣汤',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 油馍头也称麻烫、油麻、面拖、老鸹头，是中国河南省的一道特色小吃，其类似油条，又和油条不同，总之其为发面油炸后的食品，其在中国北方地区广为流传，早上吃油馍头，配上豆浆、素氽汤、肉丸子方便面或者胡辣汤是北方人习惯吃法，河南人喜欢把它当作早餐吃，口感外酥里嫩。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油馍头',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 月亮馍又叫月亮饼、饼夹粉蒸肉，是河南省郑州市的一种特色小吃，属于豫菜系，该小吃有大小之分，大者直径可超过25cm，小者只有巴掌大，该小吃各宾馆饭店均有供应，在自助餐上也能见到。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '月亮馍',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 豫、中、东部鲁西南,皖北一带的传统小吃，口感酥脆，营养丰富，是早餐的最佳选择。
  {
    province: '河南省',
    city: '郑州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '肉盒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'henanCuisine',
    cuisineCategoryName: '豫菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
