/**
 * 陕西-商洛市-美食
 * 擀面皮,搅团,商州糍粑,橡子凉粉,山阳腊肉,
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const shangluoFoodsList = [
  // 擀面皮：商洛的擀面皮有黑、白两种，不同于关中和汉中等地的面皮。
  {
    province: '陕西省',
    city: '商洛市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '擀面皮',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 搅团：本是当地百姓贫苦时的日常食品，但因其原料为杂粮，天然健康，加之做法更加精细，逐渐成为了风味小吃。搅团所用面粉必须是粗粮，多为玉米面搅团的吃法很多，浇热汤酸菜、做凉水“鱼鱼”凉调、炒食、烩搅团块等等皆可。商洛人吃搅团，大多要调辣子，调得碗里红如血方才够味。
  {
    province: '陕西省',
    city: '商洛市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '搅团',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 商州糍粑：即以土豆为主要原料烹调的膳食，是当地流行的一种小吃。制作时先将土豆去皮蒸熟，然后将蒸熟的土豆用木捶捣碎，则成为洋芋糍粑，口感细而绵软。食用时有多种方式：将糍粑切块放入酸菜汤内煮，再浇上辣椒油，色鲜味美，为“烩糍粑”；把糍粑盛入碗中，再把大蒜、花椒、海椒等各种调料放入另一碗中，再加上热的酸菜汤，用洋芋糍粑蘸着吃。
  {
    province: '陕西省',
    city: '商洛市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '商州糍粑',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 橡子凉粉：为商洛的风味小吃，是洛南县寺坡高塬村用当地特有的橡树资源来制作的。寺坡橡子凉粉的原料为成熟的橡子，把橡子打成淀粉，用泉水和制，再做凉粉。成品吃起来爽滑、筋道，十分可口。
  {
    province: '陕西省',
    city: '商洛市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '橡子凉粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 山阳腊肉：腊肉又叫熏肉，是山阳一带的特产，是山阳人请客送礼的传统佳品。每逢冬腊月，山阳家家户户都要制作腊肉，鲜肉先用各种配料腌制，经过多道工序，最后用烟火慢慢熏烤。熏好的腊肉表里一致，煮熟切成片，透明发亮，色泽透红，吃起来味道醇香，肥不腻口，瘦不塞牙。 [33]
  {
    province: '陕西省',
    city: '商洛市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '山阳腊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
