/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-11-14 18:14:33
 * @FilePath: /cooking-menu/src/views/more/wine/wine.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 主食-酒
 */
// import { lampshadedBeefScriptsList } from './riceFoodScriptContent/lampshadedBeef';
export const wineFoodsList = [
  {
    province: '甘肃省',
    city: '陇南市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '咂杆酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '甘肃省',
    city: '陇南市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '麦仁酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '梅州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '羊肉酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '梅州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '炒鸡酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '广东省',
    city: '汕尾市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '客家娘酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'cantoneseCuisine',
    cuisineCategoryName: '粤菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '贵州省',
    city: '安顺市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '安酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qianCuisine',
    cuisineCategoryName: '黔菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '贵州省',
    city: '毕节市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '彝家水花酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qianCuisine',
    cuisineCategoryName: '黔菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '河北省',
    city: '邢台市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '宁晋泥坑酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '河北省',
    city: '邢台市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '邢台古顺酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hebeiCuisine',
    cuisineCategoryName: '冀菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '珍珠果米酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '襄阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '襄阳黄酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 孝感米酒是湖北省孝感市传统的风味小吃，具有千年历史的地方名吃，选料考究，制法独特，价格低廉，它以孝感出产的优质糯米为原料，以孝感历史承传的蜂窝酒曲发酵酿制而成。孝感米酒白如玉液，清香袭人，甜润爽口，浓而不沽，稀而不流，食后生津暖胃，回味深长。
  {
    province: '湖北省',
    city: '孝感市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '孝感米酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 蛋花米酒是一种湖北武汉的特色小吃，主要作为早点食用。具有米酒的美味和鸡蛋的丰富的营养。鸡蛋与米酒的香味的相聚，给人一种心旷神怡的感觉。
  {
    province: '湖北省',
    city: '武汉市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蛋花米酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '内蒙古自治区',
    city: '赤峰市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '宁城老窖酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '内蒙古自治区',
    city: '赤峰市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '喀旗马奶酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '内蒙古自治区',
    city: '赤峰市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '赤峰啤酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '内蒙古自治区',
    city: '呼和浩特市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '马奶酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'mongolianFood',
    cuisineCategoryName: '蒙菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '扬州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '琼花露酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江西省',
    city: '赣州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '梅关春酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangxiCuisine',
    cuisineCategoryName: '赣菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江西省',
    city: '南昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '李渡酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangxiCuisine',
    cuisineCategoryName: '赣菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江西省',
    city: '萍乡市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '苏轼蜜酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangxiCuisine',
    cuisineCategoryName: '赣菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 米酒是朝鲜族爱喝的一种稻米发酵饮料。米酒是招待客人的佳品，如有客来访，主人总要端上碗自家酿制的米酒。这种酒比黄酒的色稍白一点，而且还略带甜味。
  {
    province: '吉林省',
    city: '延边朝鲜族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '米酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jilinCuisine',
    cuisineCategoryName: '吉林菜、吉菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '宁夏回族自治区',
    city: '中卫市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '黄酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'northwesternCuisine',
    cuisineCategoryName: '西北菜、宁夏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '陕西省',
    city: '渭南市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '白水杜康酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shaanxiCuisine',
    cuisineCategoryName: '陕西菜、陕菜、秦菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '山东省',
    city: '临沂市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '兰陵美酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'shangdongCuisine',
    cuisineCategoryName: '鲁菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 呷酒
  {
    province: '四川省', // 省
    city: '达州市', // 市
    district: '', // 区
    address: '', // 地方名称
    foodAvatar: '', // 美食图片
    foodName: '呷酒', // 美食名称
    foodName_en: '', // 美食英文名称
    foodCategoryCode: 'beef', // 食材类别编码
    foodCategoryName: '牛肉', // 食材类别名称
    cuisineCategoryCode: 'sichuanCuisine', // 菜系编码
    cuisineCategoryName: '川菜', // 所属菜系
    tasteCode: 'spicy', // 口味编码
    tasteName: '麻辣', // 口味名称
    menuCategoryCode: '', // 菜品分类编码
    menuCategoryName: '', // 菜品分类名称，比如：早餐，米，面，饼，菜肴，酱，酒，醋等
    cookingTypeCode: 'multiple', // 烹饪类型编码
    cookingTypeName: '腌、晾、烘、蒸、炸、炒', // 烹饪类型名称
    featuresName: '薄如纸，色红亮，味麻辣鲜脆', // 特色、特点
    // 美食详情
    detail: {
      introduction: '', // 简介
      storyBackground: '', // 故事背景
      ingredients: '', // 原料
      // 制作过程
      productionProcess: [
        {
          stepDesc: '', // 步骤描述
        },
      ],
      // 营养价值
      nutritionalValue: [
        {
          stepDesc: '', // 步骤描述
        },
      ],
      // 食用功效
      edibleEffects: [
        {
          stepDesc: '', // 步骤描述
        },
      ],
      // 做法
      practiceList: [
        {
          way: '1', // 步骤名称
          practiceDesc: '1', // 做法详情介绍
        },
      ],
    },
    shootingStatus: 0, // 拍摄状态
    scripts: 'lampshadedBeefScriptsList',
    remark: '', // 备注
    tags: null, // 标签
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0, // 是否已完成烹饪标记，0是否，1是完成
  },
  {
    province: '西藏自治区',
    city: '拉萨市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '青稞酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tibetanCuisine',
    cuisineCategoryName: '藏餐',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '云南省',
    city: '保山市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '春甜黄酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'yunnanCuisine',
    cuisineCategoryName: '滇菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '浙江省',
    city: '嘉兴市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '嘉善黄酒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'zhejiangCuisine',
    cuisineCategoryName: '浙江菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
