/**
 * 湖北-恩施土家族苗族自治州-美食
张关合渣,土家十大碗,洋芋粑粑,土家油茶汤,鲊广椒炒腊肉,公婆饼,大派火腿,榨辣椒,腊肉土豆片,张关合渣,土家十大碗,柏杨豆干,宣恩火腿,油香儿
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const enshiFoodsList = [
  // 合渣，又名懒豆腐。恩施土家人对合渣有着深厚的感情，特别是在兵荒马乱之年，由于粮食奇缺，合渣救下了不少人的性命，流传有“辣椒当盐，合渣过年”的民谚。如今，恩施人吃合渣已不是逢年过节才能吃的“奢侈品”了，平时在家里都能吃上合渣，许多餐馆更是把它当成一道特色菜上桌供应，深受顾客的青睐。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '张关合渣',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 土家十大碗在土家族已经流传几百年了。来源于当地民间节庆及办酒席时惯用的方式，其最大的特点是半荤半素、一菜两味、油而不腻，餐桌上看不到盘子，吃饭及装菜全部是蓝边大口碗。土家人生性好客、同时又爱面子，但由于以往生活贫困，无力安排好足量的菜肴，但是又想使餐桌上菜品的数量多，面子好，因此一般每桌都安排十碗菜，荤菜下面用素菜垫底，久而久之就形成了当地举办红白喜事时固定菜式，称为“土家十大碗”。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家十大碗',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '洋芋粑粑',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家油茶汤',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 鲊广椒炒腊肉是一道以鲊广椒、腊肉为主材料制作而成的土家人菜肴。鲊广椒，也称为鲊辣椒，它是以恩施本地鲜红辣椒和苞谷面（玉米面）为主要原料加工而成。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鲊广椒炒腊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 公婆饼又名“土家公婆饼”是恩施地区十大名小吃之一，因其突出的土家民族风味和特殊的制作工艺深受人们的喜爱。主要食材是面粉，主要烹饪工艺是烤。相传，清朝乾隆年间，鹤峰县有一农户唐姓人家系有一子，名十八，公婆饼三口之家以农耕为生。勤劳的老两口有一绝活的面食手艺，闲暇之时，遂做面饼到集市上换取少量的钱财与衣物。几年后，老人年事已高，儿子十八娶了媳妇，儿媳孝顺之至。把公爹公婆交给他的面饼手艺传承了过来。并且每天一大早上亲手做出各种口味的面饼端上桌子以做早餐，公爹公婆称赞不已，每天如此，一家四口其乐无穷。邻村的百姓都对此户人家敬慕不已。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '公婆饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 大派火腿是湖北省恩施土家族苗族自治州的一种特色肉类食品。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '大派火腿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 榨辣椒是以武隆仙女寨为发源地，沿乌江上至贵州、湖南吉首怀化、湖北咸丰、恩施等一带；沿长江上游至四川、下游至湖北荆州、公安、石首、洪湖，湖南澧县、常德、津市、益阳、长沙一带。在该区域有很深的消费根基，家家户户当作待客名菜，旧时女儿出嫁之前这是必备手艺。随着改革开放，人口流动，榨辣椒进入全国市场，特别是在楚菜（重庆菜）、湘菜、鄂菜、黔菜、滇菜大行其道，吃法也不断创新。传统经典菜谱：四川、重庆主要是榨辣椒炒肉（炒回锅肉、炒腊肉、炒香肠、炒腊肠）、榨辣椒炒土豆、榨辣椒炒四季豆；湖北主要是榨辣椒炒肥肠；湖南主要是榨辣椒炒肥肠、榨辣椒炒鸡蛋、榨辣椒糊鱼等。还有些地方创新的菜谱有：榨辣椒蒸山药（重庆美女独创）、榨辣椒炕野鱼、榨辣椒烤鱼等。榨辣椒，源自重庆仙女寨，但由于各地口语差异，叫法各异，四川重庆叫榨海椒（鲊海椒、渣海椒）、湖北叫榨广椒（鲊广椒）、湖南叫炸辣椒（杂辣椒）。其本质差别不大，有一定差异，但仍以重庆、湖南常德、澧县等地的榨辣椒最正宗、最有味、那个酸香硬是霸道！
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '榨辣椒',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 腊肉土豆片是恩施州特产，属土家菜系。恩施州的少数民族主要是土家族和苗族，而土家菜系以猪肉为主，犹以"腊肉"见长。"腊肉"的制作都在每年的十冬腊月，把猪杀了，分切成块，然后涂抹上盐巴、花椒等调料，以"棕叶"搓成的绳拴挂于火炕之上，任火燎烟熏……这样制作的腊肉可以放三五个月甚至半年也不会变味。每有客至，便取其中一块。先置炭火上烧烤其皮，任肉油"滋滋"作响，那诱人的香味也渐渐曼延开来……再将烧烤好的肉块丢在炒锅里，用水浸泡十来分钟，然后用刀将猪皮上那层泡软的外皮清理掉，用"刷帚"将猪肉洗净，置于甑板上分解成两指头大小的肉块，放入炒锅，加花椒、辣椒、八角香或者桂皮等物，舀生水至没肉，拿盖将锅合严，然后以文火煨炖。在煨炖的同时，取晒干的"土豆"片若干，用热水浸泡约十来分钟，至温软时取出笠于筲箕之上。待肉块煨炖到三十分钟左右时，拿筷子轻戳肉皮，肉皮松则肉熟，这时将笠于筲箕之上的"土豆"片尽数倒在锅中，再掺入少许的水炖开
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '腊肉土豆片',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 柏杨豆干是湖北省恩施土家族苗族自治州的一种地方特色菜肴，因产于利川市柏杨坝镇柏杨村而得名。2011年1月16日，恩施土家族苗族自治州人民政府将柏杨豆干工艺列为第三批非物质文化遗产保护名录，对柏杨豆干传统手工艺进行保护。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '柏杨豆干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 宣恩火腿，湖北省宣恩县特产，中国国家地理标志产品。宣恩火腿沿用中式火腿传统工艺，结合土家苗寨腌腊技术精制而成，选料考究，工艺独特，质量上乘，历史悠久，与浙江金华火腿、江苏如皋火腿、云南宣威火腿并称为“中国四大名腿”。2012年07月18日，原国家质检总局批准对“宣恩火腿”实施地理标志产品保护。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '宣恩火腿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 油香儿（儿发音）是湖北省恩施土家族苗族自治州的一种风味小吃，该菜品在当地街边、餐馆都十分普遍，是恩施人常见的小吃之一；油香儿以其价格低，制作快速，口味香酥得到人们的喜爱。
  {
    province: '湖北省',
    city: '恩施土家族苗族自治州',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油香儿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
