/**
 * 湖北-荆门市-美食
 * 
荆门八角雪枣,万寿羹,钟祥米茶,钱场霉千张,京山白花菜,长湖鱼糕,蟠龙菜,风干鸡,皮条鳝鱼
*/
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const jingmenFoodsList = [
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '荆门八角雪枣',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 万寿羹又名龟鹤延年汤，是一道湖北荆门的传统特色名吃。以龟肉和鸡肉合烹的汤菜，营养价值极高。菜名吉祥，喜庆寿筵均宜。选用荆门出产的断板龟与母鸡经过加工处理，剁成3厘米见方块，用猪油爆炒后，
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '万寿羹',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '钟祥米茶',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '钱场霉千张',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 京山白花菜为全国农产品地理标志，是湖北珍稀名产蔬菜作物之一。早在2000多年前即为贵族宴宾珍肴，唐太宗李世民品尝后赞其质优、味美，并将它定为每年的贡品。2011年被评为湖北十大名菜，授予金奖产品称号。制品口感脆爽，回味无穷，富含多种维生素、氨基酸、碳水化合物以及人体所需的钙、锌、铁、镁等微量元素。 [
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '京山白花菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 长湖鱼糕以长湖白鱼为主料，掺合淀粉、蛋清、生姜等佐料,摊成餠形，放进蒸笼，大火蒸制而成。
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '长湖鱼糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 蟠龙菜选用精瘦肉、肥膘肉、精鱼肉，调以鸡蛋、葱白、生姜、豆粉、食盐、味精等配制而成，色泽洁白，滑爽，吃肉不见肉，吃鱼不见鱼。
  // 蟠龙菜，中国名菜。又称盘龙菜、卷切，俗名剁菜，被称为“钟祥三绝”之一，湖北十大经典名菜之一。已列入《中国菜谱》，其制作技艺列入“湖北省非物质文化遗产名录”。蟠龙菜诞生于明武宗年间，得名于
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蟠龙菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 风干鸡又名刘皇叔婆子鸡，是湖北省荆门市沙洋县十里铺镇的传统名吃。这种鸡易保存又不失新鲜，醇香、软嫩，老少皆宜，深受当地老百姓喜爱。相传三国时期，孙权为联合刘备拒曹，将妹妹孙尚香嫁给了刘
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '风干鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 皮条鳝是湖北荆州的传统名菜，属于鄂菜，己有数百年历史。鳝鱼味美，且有药用价值。《名医别录》说它有补五脏、疗虚损的功效。皮条鳝鱼剔除老骨后切成长条，制熟后犹如皮条而得名。又以形如竹节，也叫
  {
    province: '湖北省',
    city: '荆门市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '皮条鳝鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
