/**
 * 湖北-荆州市-美食
 * 皮条鳝鱼,
 * 冬瓜鳖裙羹
 * 公安牛肉,松滋杜婆鸡,洪湖莲藕藕带,洪湖野鸭,* 洈水鳜鱼,笔架鱼肚,荆州鱼糕,荆州鱼糕,千张扣肉,油炸藕丸,
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const jingzhouFoodsList = [
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '公安牛肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '松滋杜婆鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '笔架鱼肚',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '洪湖莲藕藕带',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '洪湖野鸭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '洈水鳜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 此菜以肥瘦兼有的五花猪肉为原料，经煮炸，上红糖色，切成薄片，以碗扣住蒸熟，由于肉片薄如纸，形如梭，片数多，故名千张扣肉，又名梳子肉。
  {
    province: '湖北省',
    city: '荆州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '千张扣肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
