/**
 * 湖北-宜昌市-美食
 * 三峡苕酥,金箍条,凉虾,萝卜饺子,凉拌鱼腥草,香辣虾,合渣,土家腊肉,远安冲菜,土家蒸肉,踏豆饼,干烧铜鱼,顶顶糕,炕洋芋,油脆,夷陵春卷,鸡泥桃花鱼,冰凉糕,宜昌三游神仙鸡,峡口明珠汤
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const yichangFoodsList = [
  // 三峡苕酥是以三峡地区土家民间传统食品“苕丝糖”为基础，精选三峡地区沙土鲜红苕（又名番薯、甘薯或地瓜）、优质鲜糯米、鸡蛋为主要原料，采用土家民间传统工艺精制而成。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '三峡苕酥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '金箍条',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 凉虾以大米、玉米等为原料，以红糖水为调料，清凉解渴，夏季勾兑冰红糖水后饮用，风味更佳，是深受宜昌居民喜爱的饮品。由路边小贩经营，多为家庭自制。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '凉虾',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 萝卜饺子虽然也叫饺子，但其制作原料以及制作方法却与北方水饺大相径庭。北方水饺主要原料为面粉、瘦肉和蔬菜，而萝卜饺子主要原料为大米、黄豆和萝卜。北方水饺多为下水煮熟，而萝卜饺子则非下油锅炸不可，否则就不能成形。所以吃起来的时候，水饺要输萝卜饺子一段香脆。
  // 萝卜饺子是湖北宜昌市著名的传统小吃之一。萝卜饺子虽然也叫饺子，但其制作原料以及制作方法却与北方水饺大相径庭。萝卜饺子将萝卜切成丝拌上辣椒面、花椒粉、蒜（葱）苗、精盐等调料、油炸时，先在特制的弯月状铁勺中放入底浆，再放上拌好的萝卜丝作馅，再盖上浆，放入油锅中炸至金黄色即成。食之外酥内软、辣而不刺，味鲜可口。在江西赣南地区有一种萝卜馅蒸饺，用蕃薯粉做饺子皮，用萝卜剁成丁做馅，做好后清蒸即可食用，皮是透明状的。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '萝卜饺子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 鱼腥草，又名节节根、节儿根，多年生草本植物，因茎叶有鱼腥味而得名，全草可入中药。宜昌市境内均有生长，多为野生，还有人工载植。一年四季都有上市（春季最多），以茎肥嫩者为佳。配姜、蒜泥、酱油、醋、葱段、味精、麻油等即成，此菜脆嫩、清香、爽口，有清热、解毒、消炎之功效。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '凉拌鱼腥草',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 香辣虾是一道汁浓、麻辣味浓，肉质紧韧爽脆的名菜。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '香辣虾',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 合渣又名懒豆花，是土家族的传统小吃。合渣的制作比较简单，只是在开头“推”的阶段稍辛苦些，因此人们称制作合渣为推合渣，其制作程序是：将黄豆洗净用水泡胀后，连豆带水在石磨上一转一转地磨成浆，架火煮开，然后放入切好的新鲜萝卜菜叶，再煮开，就制成了一锅乳白带绿的合渣。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '合渣',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 先将花椒、八角香、山胡椒等佐料合盐炒香磨研成粉，待猪羊修净破腹后即砍下头、腿、前胛，腌好入缸，所余按五、六斤一块砍成条形，逐块腌好，依层而放，每层再撒上盐和佐料，如此腌制十日左右即取出上炕。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家腊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 风味奇特的冲（音“宠”）菜是一道小菜，这道小菜有三个特点：一是好看，黄绿相间，鲜嫩悦目；二是好吃，清脆爽口，酸咸适度；三是好闻，香气扑鼻，暗藏冲劲。初次吃冲菜的人，刚一入口，正当你感觉良好之时，冷不防一股冲味直钻鼻腔：轻者，令你鼻腔痒痒；重者，令你喷涕连连——这正是冲菜之所以名。但这种冲劲很快就过去了，冲过之后则余味无穷。冲菜是一种开胃提神的小菜，每每一碟上桌，很快就被抢得精光，倍受食客青睐，故又得名“宠菜”。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '远安冲菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 土家蒸肉属于鄂菜系。由玉米面、鲜肉、南瓜、土豆、炸辣椒制成。然后把做好的蒸肉盛进土家蒸蒸肉的专用蒸格并放于锅里蒸，约半个小时光景见蒸格有大气冒出即可食用。其香奇醇其味奇美，鲜香，色香味俱全。实是土家一大特色小吃。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家蒸肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 踏豆饼是湖北当阳的传统名吃。每当岁尾，踏豆饼就跟办年货一样，成为每家每户必备之物。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '踏豆饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 宜昌以上长江干支流中盛产的铜鱼与鳊鲂齐名。鱼身呈古铜色，身体圆，头小肉厚，肉质特别细嫩，味道异常鲜美。干烧铜鱼是将一斤多重的铜鱼配以肉丁、辣椒、蒜、姜、酱油、高汤、白糖等佐料制作，色泽红亮，红油包汁，味香鲜嫩。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '干烧铜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 顶顶糕，是湖北宜昌、恩施、荆门、荆州等地的特色糕类小吃之一。顶顶糕以大米粉、糯米粉、红糖粉为原料，放入特制的小木格内，加上一点红糖桂花，放在滚水的瓶口利用那浓浓的蒸汽，只需两三分钟，一块块圆圆的小白糕就做成了。其特点是松软带糯，味清香甜正。顶顶糕具有红糖可以补血，补气的功效。由于价格实惠、口感香甜，深受人们的喜爱。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '顶顶糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 炕洋芋是湖北西部地区流行的美食。“炕”是湖北省西部地区的方言，是煎炒焖炸之外的一种做菜方式，介于用少量食用油煎与炸之间的一种烹饪方式。“洋芋”就是土豆。俗话说“高山的洋芋，低山的苕。炕熟后，洋芋吃在嘴里感觉不油有种烤熟的香甜感。”就是说高山上的洋芋味道好，在湖北西部高山上出产的洋芋味道都非常受食客的欢迎，提出了做洋芋类的家常菜，做恩施地区流行的“炕洋芋”更是一绝，“恩施炕洋芋”已经成为恩施地区的一张名片。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '炕洋芋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 油脆是湖北宜昌的传统小吃之一，用糯米蒸成糍巴，包入白糖和芝麻馅，做成棱子形，炸成金黄色即成。食之外脆内软、香甜可口。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油脆',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 夷陵春卷是湖北省宜昌市传统小吃。用鸡蛋、面粉制成薄皮，卷入稍加煸炒的韭菜、腊肉、豆腐干、香菌（或冬菇）,油炸至金黄色即可食，此菜外酥内嫩、香软可口，一般在农历新年期间家庭自行制作，深受宜昌市民喜爱。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '夷陵春卷',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 鸡泥桃花鱼是长江三峡附近的宜昌城的一道传统的名菜，用桃花鱼、鸡脯肉、 鱼等原料制成的，成菜在汤碗里边犹如一朵朵清新艳丽的桃花，特别惹人喜爱。此汤汤味清香，营养丰富，乃汤中上品。桃花鱼是这道汤菜的精华之所在，不过这里的桃花鱼却并不是鱼，而是一种透明的腔肠动物，形似海蜇，又被称作为“桃花水母”。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鸡泥桃花鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '冰凉糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 三游神仙鸡，是湖北宜昌市一道传统菜，系选用肥嫩仔鸡为原料，经宰杀治净后，以整鸡置砂钵用多种调味料腌渍，再加高汤及香料、冰糖等调料烧沸，然后移小火（火靠）至汁浓鸡熟装盘。色亮香醇，原汁原味。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '宜昌三游神仙鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 1.闻名中外的游览胜地——长江三峡，它西起奉节县的白帝城，东至宜昌市的南津关，号称七百里画廊，无山不奇，无峰不秀。峡口建有举世闻名的葛洲坝水电站，一到晚上，灯火辉煌，似颗颗明珠。宜昌市的
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '峡口明珠汤',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
