/**
 * 湖北-宜昌市-美食
 * 凉拌鱼腥草,香辣虾,合渣,土家腊肉,远安冲菜,土家蒸肉,
 * 干烧铜鱼,
 * 鸡泥桃花鱼,
 * 宜昌三游神仙鸡,峡口明珠汤
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const yichangFoodsList = [
  // 鱼腥草，又名节节根、节儿根，多年生草本植物，因茎叶有鱼腥味而得名，全草可入中药。宜昌市境内均有生长，多为野生，还有人工载植。一年四季都有上市（春季最多），以茎肥嫩者为佳。配姜、蒜泥、酱油、醋、葱段、味精、麻油等即成，此菜脆嫩、清香、爽口，有清热、解毒、消炎之功效。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '凉拌鱼腥草',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 香辣虾是一道汁浓、麻辣味浓，肉质紧韧爽脆的名菜。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '香辣虾',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 合渣又名懒豆花，是土家族的传统小吃。合渣的制作比较简单，只是在开头“推”的阶段稍辛苦些，因此人们称制作合渣为推合渣，其制作程序是：将黄豆洗净用水泡胀后，连豆带水在石磨上一转一转地磨成浆，架火煮开，然后放入切好的新鲜萝卜菜叶，再煮开，就制成了一锅乳白带绿的合渣。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '合渣',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 先将花椒、八角香、山胡椒等佐料合盐炒香磨研成粉，待猪羊修净破腹后即砍下头、腿、前胛，腌好入缸，所余按五、六斤一块砍成条形，逐块腌好，依层而放，每层再撒上盐和佐料，如此腌制十日左右即取出上炕。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家腊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 风味奇特的冲（音“宠”）菜是一道小菜，这道小菜有三个特点：一是好看，黄绿相间，鲜嫩悦目；二是好吃，清脆爽口，酸咸适度；三是好闻，香气扑鼻，暗藏冲劲。初次吃冲菜的人，刚一入口，正当你感觉良好之时，冷不防一股冲味直钻鼻腔：轻者，令你鼻腔痒痒；重者，令你喷涕连连——这正是冲菜之所以名。但这种冲劲很快就过去了，冲过之后则余味无穷。冲菜是一种开胃提神的小菜，每每一碟上桌，很快就被抢得精光，倍受食客青睐，故又得名“宠菜”。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '远安冲菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 土家蒸肉属于鄂菜系。由玉米面、鲜肉、南瓜、土豆、炸辣椒制成。然后把做好的蒸肉盛进土家蒸蒸肉的专用蒸格并放于锅里蒸，约半个小时光景见蒸格有大气冒出即可食用。其香奇醇其味奇美，鲜香，色香味俱全。实是土家一大特色小吃。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '土家蒸肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 宜昌以上长江干支流中盛产的铜鱼与鳊鲂齐名。鱼身呈古铜色，身体圆，头小肉厚，肉质特别细嫩，味道异常鲜美。干烧铜鱼是将一斤多重的铜鱼配以肉丁、辣椒、蒜、姜、酱油、高汤、白糖等佐料制作，色泽红亮，红油包汁，味香鲜嫩。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '干烧铜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 鸡泥桃花鱼是长江三峡附近的宜昌城的一道传统的名菜，用桃花鱼、鸡脯肉、 鱼等原料制成的，成菜在汤碗里边犹如一朵朵清新艳丽的桃花，特别惹人喜爱。此汤汤味清香，营养丰富，乃汤中上品。桃花鱼是这道汤菜的精华之所在，不过这里的桃花鱼却并不是鱼，而是一种透明的腔肠动物，形似海蜇，又被称作为“桃花水母”。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鸡泥桃花鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 三游神仙鸡，是湖北宜昌市一道传统菜，系选用肥嫩仔鸡为原料，经宰杀治净后，以整鸡置砂钵用多种调味料腌渍，再加高汤及香料、冰糖等调料烧沸，然后移小火（火靠）至汁浓鸡熟装盘。色亮香醇，原汁原味。
  {
    province: '湖北省',
    city: '宜昌市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '宜昌三游神仙鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'hubeiCuisine',
    cuisineCategoryName: '楚菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
