/**
 * 辽宁-阜新市-美食
 * 蒙族馅饼,清沟鱼宴,喇嘛糕,喇嘛粥
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const fuxinFoodsList = [
  // 阜新地区蒙古族的一种风味面食，距今已有三百多年的历史。最早是以当地特产的荞麦面制皮，牛羊猪肉为馅，采用干烙水烹的方法制成。它以面稀、皮薄、馅细为特点，烙制后形如铜锣，外焦里嫩，饼面上油珠闪亮，透过饼皮可见里面肉似玛瑙，菜如翡翠，红绿相间。
  {
    province: '辽宁省',
    city: '阜新市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蒙族馅饼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 彰武县境内的大清沟，水清、沟深，藻类繁多，为鱼类的生息、繁殖创造了良好的环境。这里的鱼，由于摄食自然食物生长而成，因此，肉质细腻，无异味，并有着天然绿色食品的美誉。大清沟盛产鲤鱼、鲢鱼、鲫鱼、鲶鱼、草鱼、等30多种鱼类，最大的鱼达40多公斤。
  {
    province: '辽宁省',
    city: '阜新市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清沟鱼宴',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 喇嘛糕（京式）是阜新境内蒙古族的一种传统糕点。它选用精制面粉、白沙糖、鸡蛋为主要原料，以瓜籽儿仁、青红丝、桂花为辅助原料，放入烤炉烤制而成。其特点是洁白如雪、味道香甜、口感松软，富有弹性
  {
    province: '辽宁省',
    city: '阜新市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '喇嘛糕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // “喇嘛粥”过去是指寺庙内由喇嘛用肉、骨头和米熬的粥，所以叫“喇嘛粥”，起源于蒙古佛教喇嘛寺庙活动，一般是用羊肉熬成的玉米粥、小米粥、大米粥,由喇嘛施舍给香客、施主。“喇嘛粥”不仅仅是在寺庙
  {
    province: '辽宁省',
    city: '阜新市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '喇嘛粥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
