/**
 * 辽宁-辽阳市-美食
 * 塔糖,汤河鲜鱼,老世泰糕点,老杨头烧鸡,
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const liaoyangFoodsList = [
  // 塔糖不仅具备着特殊的风味而且它的外形也很美，有如梅花形并多孔，吃起来酥脆，清香可口，色泽洁白细致，经暑不变。
  // 各类鲜鱼皆取自辽宁省未被污染的水库--汤河水库，主要品种有：鲢鱼、鲫鱼、老头鱼、鲤鱼、草鱼、岛子鱼、麻口、公鱼、嘎牙鱼、虫虫鱼、黑鱼等30多种，年可销售鲜鱼近15万公斤。经过精心加工，可制成汤河全鱼宴。汤河鲜鱼肉质鲜嫩，味道清鲜，是弓长岭区的特色餐饮品牌，在省内外远近闻名。2002年，汤河“滋补鱼头”被省旅游系统评为“辽宁省十大风味食品”。
  {
    province: '辽宁省',
    city: '辽阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '汤河鲜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 采用4个月出栏的小笨鸡，用独特的材料熏制，不使用防腐剂，不使用化学添加剂 ，具有味道鲜美，肉嫩香滑，是不可多得的美味佳肴。被辽阳市政府命名为“辽阳市名牌”。
  {
    province: '辽宁省',
    city: '辽阳市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '老杨头烧鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
