/**
 * 辽宁-盘锦市-美食
 * 干煎河刀鱼,碱蓬菜团子,大米嘎巴
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const panjinFoodsList = [
  // 干煎河刀鱼是一种美食，主要原料是河刀鱼等。
  {
    province: '辽宁省',
    city: '盘锦市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '干煎河刀鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 碱蓬菜团子是独特的农家风味，主料是肉馅200克、虾胶100克,是先将肉馅、虾胶、碱蓬沫放入调料蛋清向一个方向搅拌使其上劲后加入淀粉拌匀放入6层热油锅里浸炸3分钟即可（在碱蓬缺少的季节，有时也用茼蒿沫代替）。
  {
    province: '辽宁省',
    city: '盘锦市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '碱蓬菜团子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'liaoningCuisine',
    cuisineCategoryName: '辽宁菜、辽菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
