/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-10-20 19:04:17
 * @FilePath: /cooking-menu/src/views/asia/eastAsia/china/mockData/jiangsuProvince/suzhou.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 江苏-苏州市-美食
 * 
生煎馒头,油氽紧酵,半紧酵小笼,半紧酵蟹粉小笼,小笼馒头,绉纱汤包,蟹粉汤包,香菇青菜素包,鲜肉大包,鲜肉中包,豆沙馒头,开花馒头,荷花馒头,寿桃包,秋叶包,素菜烧卖,凤尾烧卖,蟹粉烧卖,虾仁烧卖,金鱼烧卖,鲜肉蒸饺,四喜蒸饺,青菜饺,蝴蝶饺,孔雀饺,鸡冠三角饺,知了饺,沈永兴馒头,桂花糖油山芋,桂花糖芋艿,焐酥豆糖粥,桂花鸡头肉,八宝鸡头肉,桂花焐熟藕,鲜肉棕,灰汤棕,白沙棕,绿豆棕,猪油夹沙棕,三角棕,小脚棕,笔棕,枣泥麻饼,蜜汁豆腐干,虾子酱油,清汤鱼翅,母油整鸡,太湖莼菜汤,翡翠虾斗,松鼠桂鱼,叫化鸡,松鼠桂鱼,响油鳝糊,蟹粉蹄筋,清溜虾仁,氽糟,母油整鸡,太湖莼菜汤,雪花蟹斗,樱桃肉,酱汁肉,薰鱼,（鱼巴）肺汤,三件子,蜜汁火方,暖锅,枣泥拉糕,轻糖松子,粽子糖,浇切片,三色松子软糖,脆松糖,松子南枣糖,金丝蜜枣,奶油话梅,金丝金桔,白糖杨梅,九制陈皮,
苏州小吃是中国四大小吃之一（南京夫子庙小吃、上海城隍庙小吃、苏州玄妙观小吃和湖南长沙火宫殿小吃并称为中国四大小吃）。“松鹤楼”是老字号的苏式餐馆；“老苏州茶酒楼”以传统苏帮菜而闻名；“朱鸿兴面馆”和“绿扬馄饨”等物美价廉，比较适合大众消费。遍布苏州的面店，表明浇头品种很多、讲究汤水的苏式面条是广受欢迎的小吃。 [25]
美食街：太监弄、十全街、学士街、李公堤、凤凰街,碧凤坊、李公堤为中国餐饮文化名街。
苏式招牌菜：松鼠桂鱼、响油鳝糊、蟹粉蹄筋、清溜虾仁、氽糟、母油整鸡、太湖莼菜汤、雪花蟹斗、樱桃肉、酱汁肉、薰鱼、（鱼巴）肺汤、三件子、蜜汁火方、暖锅、枣泥拉糕等。
苏式糖果：轻糖松子、粽子糖、浇切片、三色松子软糖、脆松糖、松子南枣糖等。
苏式蜜饯：苏州制作蜜饯的历史可上溯到三国时代，清代是苏式蜜饯的鼎盛时期，其中以“张祥丰”最为著名，历来是“宫廷食品”。苏式蜜饯现有160多个品种，以金丝蜜枣、奶油话梅、金丝金桔、白糖杨梅、九制陈皮最为著名。
*/
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const suzhouFoodsList = [
  {
    province: '江苏省',
    city: '苏州市',
    district: '昆山市',
    address: '',
    foodAvatar: '',
    foodName: '万三蹄',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '昆山市',
    address: '',
    foodAvatar: '',
    foodName: '众星捧月',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '八宝船鸭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '叫化童鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '叫花子鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '咕咾肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '太湖大闸蟹',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '松子肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '板鸭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清炖甲鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '溜子鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '炖生敲',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '炖菜核',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '烤方',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '白汁元鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '白汁圆菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '睢宁香肠',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '碧螺虾仁',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖醋排骨',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖醋鳜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '红烧沙光鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '纪妃伴龙颜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '肉脯',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '肉酿生麸',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '胭脂鹅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '船点',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '苏式酱肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '荷花铁雀',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '莼菜塘鱼片',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '藏书白切羊肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '西瓜鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '豆腐花',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '阳澄湖大闸蟹',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '雪花蟹汁',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '青团子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '香菇炖鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鸡油菜心',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鸭包鱼翅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '黄泥煨鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '龙门鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '碧螺虾',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鸡茸蛋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '枪虎尾',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '拆烩大鱼头',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '银芽鸡丝',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '参麦甲鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '三丝鱼卷',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鲜熘虾仁',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '软熘鲈鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '芙蓉鱼片',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清炒蟹粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '松鼠色',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: '',
    cuisineCategoryName: '',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [
        {
          stepDesc: '',
        },
      ],
      nutritionalValue: [
        {
          stepDesc: '',
        },
      ],
      edibleEffects: [
        {
          stepDesc: '',
        },
      ],
      practiceList: [
        {
          way: '1',
          practiceDesc: '1',
        },
      ],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '泡泡馄饨',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '油氽紧酵',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '半紧酵小笼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '半紧酵蟹粉小笼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '桂花糖芋艿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '桂花鸡头肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '八宝鸡头肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '桂花焐熟藕',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清汤鱼翅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '母油整鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '翡翠虾斗',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '松鼠鳜鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '叫化鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蟹粉蹄筋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '清溜虾仁',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '雪花蟹斗',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '樱桃肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '酱汁肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '薰鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '三件子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蜜汁火方',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '暖锅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '轻糖松子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '浇切片',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '奶油话梅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '金丝金桔',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '白糖杨梅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '江苏省',
    city: '苏州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '九制陈皮',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'jiangsuCuisine',
    cuisineCategoryName: '江苏菜、苏菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
