/**
 * 广西-河池市-美食
 *
 * 烤香猪,五色饭,都安生榨粉,龙岸菜包,七百弄鸡,瑶寨五香熏鱼
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const hechiFoodsList = [
  // 这是来自毛南族的传统美食哦。香猪的全名是环江香猪，产自环江县东兴乡、明伦乡。香猪的发源地就是在这里。由于这里有独特的禾草，是专门用来烤香猪的，所以除了本地外，其他地方的烤香猪都远没有其正宗。
  // 烧出来的香猪吃起来清脆可口，香气四溢到心间，并且一点腥味都没有，吃起来也不会腻歪，非常美味哦。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '烤香猪',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 这是来自壮族的传统美食。在壮族的古老相传中，三月初三是始祖布洛陀的诞辰，所以百姓们在这一天是要祭拜的，当天会有传统的节日，譬如：抢花炮、抛绣球等。再就是吃这一方面，每一户人家都会去做五色糯米饭。
  // 其中的五色是指红、黄、黑、紫、白五色糯米，经过传统方式的蒸煮，使得做出来的米饭味道清香，吃起来也特别香软。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '五色饭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 它是河池当地的传统美食，从民间流传出来的说法是，都安生榨粉最早起始于宋朝皇祐四年，到现在已经经历了千年时间的磨合。
  // 它不止是河池的传统小吃，也是传遍广西的著名小吃。要是说到它的味道，那真是色味鲜美，物美价廉，来了一定不要错过呢。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '都安生榨粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 当逢年过节时，龙岸菜包是仫佬族人必做的菜肴，做好后拿来去庆贺。蒸好一笼龙岸菜包后，大老远就能闻到阵阵清香，一口咬下去鲜香可口，虾的鲜味在嘴里留有余香，怎能让人不上瘾呢。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '龙岸菜包',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 它来自于广西河池大化瑶族自治县，在瑶族史诗《密洛陀古歌》中就有对七百弄鸡这一神鸡的记载。
  // 神鸡自有神鸡的奇特之处，被放养不圈养的它，鸡肉更结实且细嫩，皮下的脂肪也较普通的鸡少，吃起来那叫一个味美甘香。很多时候大化人都要给七百弄鸡举办个选美比赛，让人津津乐道呀。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '七百弄鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 瑶寨五香熏鱼是弄场瑶家传统的腌制鱼，是一种专门用来招待贵客的奇特菜肴。一拿出来，那股带着浓郁的姜、蒜、酒、芬芳的金黄鱼干就呈现在客人眼前。
  // 综合起来说，广西菜点由南宁、桂林、柳州、梧州等城市菜和壮族、瑶族、京族、侗族等少数民族菜组成。少数民族的小吃、点心非常有特色。菜肴取料奇特，制作也极有个性。
  {
    province: '广西壮族自治区',
    city: '河池市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '瑶寨五香熏鱼',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
