/**
 * 广西-钦州市-美食
 * 白鸽粥,小董麻通,钦州黄瓜皮,钦州猪脚粉,灵山大粽,蚝油柚皮鸭
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const qinzhouFoodsList = [
  // 白鸽粥，一种粥类食物。将洗净的枸杞子和米放入沙锅，加白鸽肉及少量水，文火煨粥，粥成加入香精等调料，味道鲜美。
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '白鸽粥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 小董麻通是钦州市钦北区小董出产的地方名牌小食品。麻通是一种特色小吃，主要原料为上等糯米、白糖、芝麻、茶油、饴糖,因用芝麻包裹，内如通草而得名麻通。麻通虽然简单，但制作过程却很复杂。具有
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '小董麻通',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 钦州黄瓜皮，广西壮族自治区钦州市特产，全国农产品地理标志。钦州市种植黄瓜和加工黄瓜皮早在宋代已十分盛行。钦州黄瓜皮是精选钦州黄瓜经传统方法秘制加工而成，具有嫩脆、酸中带甜、香味浓、口感好、增加食欲等特点，风味独特。钦州黄瓜皮还含大量对人体有益的乳酸菌，以及具有生物活性发酵生成物，食用有开胃消腻的功能，是人们喜爱的一种食品。近年来钦州市采用新的加工技术，把钦州黄瓜皮进行加工保鲜处理，使其成为含有多种氨基酸，口感更好，开袋即食。2014年7月28日，原中华人民共和国农业部正式批准对“钦州黄瓜皮”实施全国农产品地理标志登记保护。
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '钦州黄瓜皮',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 钦州猪脚粉是广西壮族自治区钦州市的一道传统名小吃，属于桂菜；俗话说；钦州猪脚粉，神仙也打滚。该菜品是是钦州的招牌美食。钦州猪脚粉选当地特有的上好米粉或河粉，配以调制好的熟猪脚，加入多种佐料而成，猪脚色泽艳丽、有曲折感，肥而不腻，脆而不硬。
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '钦州猪脚粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 灵山大粽是采用灵山优质糯米、野生粽巴叶、板粟、虾米、猪肉、猪脚、灵山特色腊味（腊鸭，腊肉）绿豆等DIY配料，根据民间传统工艺精制而成，口感，体形与其他地方的四角粽有别。
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '灵山大粽',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 蚝油柚皮鸭是钦州市一道美味佳肴。
  {
    province: '广西壮族自治区',
    city: '钦州市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '蚝油柚皮鸭',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
