/**
 * 广西-玉林市-美食
 *
 * 玉林牛巴, 鲜虾肠粉, 玉林牛腩粉, 海鲜大肉田螺, 桂花银虾饺, 玉林肉蛋, 酥肉地豆, 鲍鱼酥, 玉林云吞,玉林酸料
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const yulinFoodsList = [
  // 玉林牛巴，广西壮族自治区玉林市特产，中国国家地理标志产品。南宋时，玉林牛巴始制，已有800多年前的加工历史；玉林牛巴颜色半透明，色似咖啡，油亮，香味浓郁，咸甜适口，鲜美爽口，韧而不坚，具有“甘香味道妙”的特点，是玉林最负盛名的传统特色风味小吃。2011年7月6日，原国家质检总局批准对“玉林牛巴”实施地理标志产品保护。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '玉林牛巴',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 鲜虾肠粉是广西玉林地方特色小吃之一，属于粤菜系。选用优质大米磨成浆加馅蒸制而成。馅的主料有新鲜虾仁、瘦肉、鸡蛋、竹笋（或马蹄）、蒜茎、葱、韭菜,配以花生油、生抽、蒜米调制好的味汁即可食用。口感鲜嫩、爽口怡人。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鲜虾肠粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 牛腩粉是著名的传统风味食品。因以调制好的熟牛腩做佐料而得名。起于民间，解放前就已出名。已遍及两广。 将选好的牛腩、牛筋等用沸水“飞过”捞起过冷水。中火起镬，下料把牛腩炒至收水后，配以沙姜、甘松、草果等煮30-40分钟即可。将炖好的牛腩、米粉下碗，然后把牛腩汤、骨头汤、肉丸调味下碗即成。清香、可口，富含高蛋白。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '玉林牛腩粉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 海鲜大肉田螺是广西玉林十大特色小吃之一，先上好的大田螺，敲掉螺尾煮熟，将猪肉、木耳等配料剁成馅酿入田螺内，再和鸡肉、螃蟹一同下锅煮熟即可。其特点是味美鲜甜，营养丰富。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '海鲜大肉田螺',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 桂花银虾饺是一道菜品，主料为桂花。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '桂花银虾饺',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 玉林肉蛋又称肉丸，是玉林的地方特色小吃之一。玉林肉丸洁白、嫩滑、松脆、无 渣、味鲜美，富弹性，从高处扔下，可弹起10--20厘米，以猪肉，牛肉制作而成。民国时期，玉林的酒楼、饭店多有肉丸售。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '玉林肉蛋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // 酥肉地豆是广西玉林十大特色小吃之一，主要材料是猪肉、地豆（花生）。
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '酥肉地豆',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  // <主料>:鲍鱼粒面粉<辅料>笋粒,马蹄粒<调料>:精盐,味精,猪油,鲍汁
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '鲍鱼酥',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '玉林云吞',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
  {
    province: '广西壮族自治区',
    city: '玉林市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '玉林酸料',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'guiCuisine',
    cuisineCategoryName: '桂菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    isCookFlag: 0,
  },
];
