/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-10-20 19:04:17
 * @FilePath: /cooking-menu/src/views/asia/eastAsia/china/mockData/tianjin/index.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 天津-天津市-美食
* 曹记驴肉,冠生园八珍羊腿,陆记烫面炸糕,白记水饺,芝兰斋糕干,大福来锅巴菜,石头门坎素包,* 糖炒栗子,明顺斋什锦烧饼,羊汤,上岗子面茶,王记麻花（又称馓子麻花）,豆香斋牛肉香圈,豆皮卷圈,白记水饺,水爆肚,煎焖子,花样馃子,怪味果仁,石头门坎素包,罗汉肚,熟梨糕,皮糖张,北塘海鲜,狗不理包子,十八街麻花,耳朵眼炸糕,糖礅,熟梨糕,茶汤儿,果仁张,崩豆张,面茶,杨村糕干,煎饼馃子,锅巴菜,老豆腐,果子,烫面炸糕,卷圈,荷包蛋,糖果子,果篦儿,
天津三绝：天津三绝历来有两种说法：其一是被称为天津风味小吃“三绝”的狗不理包子、十八街麻花和耳朵眼炸糕；其二是被称为天津民间工艺“三绝”的泥人张彩塑、杨柳青年画和风筝魏风筝。
特色小吃：糖礅、熟梨糕、茶汤儿、果仁张、崩豆张、面茶、杨村糕干。
特色早点：煎饼馃子、锅巴菜、老豆腐、果子、烫面炸糕、卷圈、荷包蛋、糖果子、果篦儿。
天津特产：天津甘栗、天津冬菜、天津大白菜、独流老醋、狗不理包子、十八街麻花、耳朵眼炸糕。
 */
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const tianJinFoodsList = [
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '曹记驴肉',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '冠生园八珍羊腿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '芝兰斋糕干',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '大福来锅巴菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '王记麻花（又称馓子麻花）',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '豆香斋牛肉香圈',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '豆皮卷圈',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '煎焖子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '花样馃子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '罗汉肚',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '皮糖张',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '北塘海鲜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖礅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '茶汤儿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '果仁张',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '崩豆张',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '煎饼馃子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '锅巴菜',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '果子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '荷包蛋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '糖果子',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  {
    province: '天津市',
    city: '天津市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '果篦儿',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'tianjinCuisine',
    cuisineCategoryName: '天津菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];

console.log(
  '天津天津天津天津天津天津天津天津省有： ',
  tianJinFoodsList.length,
  tianJinFoodsList.map((item) => item.foodName),
);
