/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-10-20 19:04:17
 * @FilePath: /cooking-menu/src/views/asia/eastAsia/china/mockData/hainanProvince/sanya.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2023-10-20 19:04:17
 * @FilePath: /cooking-menu/src/views/asia/eastAsia/china/mockData/hainanProvince/sanya.ts
 * @Description:
 *
 * Copyright (c) 2023 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 海南-三亚市-美食
* 红烧梅花参,
爆炒夜光螺,羊栏酸鱼汤,椰肉虾仁猪骨汤,藤桥排骨,槟榔花鸡,南海鲜鲍,疍家咸鱼煲,三亚海鲜火锅,
南大辣椒蟹,南山素斋,


 * 
// 红烧梅花参
// 槟榔花鸡




*/
// import { lampshadedBeefScriptsList } from './templateFoodScriptContent/lampshadedBeef';
export const foodsStr = '';
export const sanyaFoodsList = [
  // 梅花红烧参的主料为水发梅花参，主要配料有油菜和百灵菇等。把泡发后的梅花参从中间切成两半，用开水烫透，然后将水控净。经大厨烹饪，配上新鲜的百灵菇，味道嫩滑鲜甜，具有滋阴补肾，增强机体免疫力之功效。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '红烧梅花参',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 安游夜光螺是海南一带的风味名菜，属于海南菜。产自安游近海，新鲜味美。连着螺壳一起用辣椒爆炒，螺肉爽脆重又带有一股韧劲，甚有嚼头。又有白灼的做法，保留了螺肉的自然鲜美，连外地人也能品得出里面的“甜”。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '爆炒夜光螺',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 藤桥排骨是一道色香味俱全的传统名菜，属于海南菜。被称三亚美食一绝，名列三亚10大美食之榜。制品红黄敞亮，外脆里香、味美醇香，老少咸宜。由于放蜂蜜腌制，入口酥脆，味鲜微甜，有点象广味叉烧，可是又不象，归正回味无穷。配上一菜一汤，两小我吃上半斤排骨就饱得不可。那排骨的余香，一向如此残留在唇齿之间，久久未消，实在是爽。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '藤桥排骨',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 槟榔花鸡是一道简单的家常菜，主料是三亚本地农家鸡、槟榔花。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '槟榔花鸡',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 南海鲜鲍是三亚十大名菜之一，主要制作材料有新鲜鲍鱼、葱、姜等。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '南海鲜鲍',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 疍家咸鱼煲是一道美味可口的传统名肴，属于海南菜。三亚十大名菜之之一。疍家渔民常年居于海上，捕到上好的鱼（多以红鱼为主要材料）时，将其放在船只甲板晒制，在海风和海面骄阳的共同作用下，制作出无任何人工添加剂、肉质紧实耐嚼的精品咸鱼干。疍家咸鱼，鱼香浓郁，煲以五花肉，实在是美味无比，佐酒下饭均可称职。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '疍家咸鱼煲',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 三亚海鲜火锅是海南一带的传统风味名肴，属于海南菜。三亚十大名菜之三。取材三亚本地海鲜，虾、蟹、螺、贝、鱼应有尽有，各取所好。锅底仅入姜片、蒜苗等调味，旨在保留原汁原味，尤其凸显海鲜特有的清甜和营养，辅以各家秘制蘸酱，尤其美味。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '三亚海鲜火锅',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // 海南特色辣味菜．出自三亚市南中国大酒店厨师之手，故以"南大"命名．海南盛产各种花蟹，烹调多以“清蒸”或“姜葱炒”。此菜吸取川湘烹法，结合本地口味，采用辣椒油炸法，成菜焦脆、香辣，余味无穷。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '南大辣椒蟹',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
  // “南山素斋”是天下一绝，它集寺庙素斋之精华，融宫廷素斋和民间素斋之风格，兼纳南北地方风味于一体，运用现代烹饪技艺，形成了独特的南山饮食文化，被海南省定为“国宾接待点”。
  {
    province: '海南省',
    city: '三亚市',
    district: '',
    address: '',
    foodAvatar: '',
    foodName: '南山素斋',
    foodName_en: '',
    foodCategoryCode: 'beef',
    foodCategoryName: '牛肉',
    cuisineCategoryCode: 'qiongCuisine',
    cuisineCategoryName: '琼菜',
    tasteCode: 'spicy',
    tasteName: '麻辣',
    menuCategoryCode: '',
    menuCategoryName: '',
    cookingTypeCode: 'multiple',
    cookingTypeName: '腌、晾、烘、蒸、炸、炒',
    featuresName: '薄如纸，色红亮，味麻辣鲜脆',
    detail: {
      introduction: '',
      storyBackground: '',
      ingredients: '',
      productionProcess: [{ stepDesc: '' }],
      nutritionalValue: [{ stepDesc: '' }],
      edibleEffects: [{ stepDesc: '' }],
      practiceList: [{ way: '1', practiceDesc: '1' }],
    },
    shootingStatus: 0,
    scripts: 'lampshadedBeefScriptsList',
    remark: '',
    tags: null,
    recommendStoreName: '',
    recommendStoreAddress: '',
    isGoTo: 0,
    isCookFlag: 0,
  },
];
