/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2024-07-12 11:50:38
 * @FilePath: /cooking-menu/src/views/more/formulasConversion/formulasMarinade.data.ts
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 主食-配方换算-卤味、卤水配方
 */

// import { lampshadedBeefScriptsList } from './riceFoodScriptContent/lampshadedBeef';
const ar = [
  '主材',
  '花椒',
  '胡椒掺合粉(1:1)',
  '醋',
  '酱油',
  '辣椒油',
  '蒜水各一勺',
  '白芝麻',
  '味精',
  '鸡精适量',
];
const list = {
  title: '',
  remark: null,
  starLevel: 1,
};
ar.map((item, i) => {
  list['itemName' + i] = item;
  list['itemVal' + i] = i;
  list['itemUnit' + i] = null;
});
console.log('配方换算', list);
export const formulasFoodsListMarinade = [
  {
    title: '五香卤水配方(40斤水)',
    remark: null,
    starLevel: 5,
    itemName0: '水',
    itemVal0: 40,
    itemUnit0: '斤',
    itemName1: '八角',
    itemVal1: 90,
    itemUnit1: null,
    itemName2: '桂皮',
    itemVal2: 60,
    itemUnit2: null,
    itemName3: '小茴香',
    itemVal3: 70,
    itemUnit3: null,
    itemName4: '良姜',
    itemVal4: 30,
    itemUnit4: null,
    itemName5: '甘草',
    itemVal5: 30,
    itemUnit5: null,
    itemName6: '白蔻',
    itemVal6: 50,
    itemUnit6: null,
    itemName7: '陈皮',
    itemVal7: 20,
    itemUnit7: null,
    itemName8: '白芷',
    itemVal8: 60,
    itemUnit8: null,
    itemName9: '香叶',
    itemVal9: 30,
    itemUnit9: null,
    itemName10: '香菜籽',
    itemVal10: 30,
    itemUnit10: null,
    itemName11: '丁香',
    itemVal11: 12,
    itemUnit11: null,
    itemName12: '草果',
    itemVal12: 40,
    itemUnit12: null,
    itemName13: '千里香 ',
    itemVal13: 16,
    itemUnit13: null,
    itemName14: '肉蔻',
    itemVal14: 20,
    itemUnit14: null,
    itemName15: '冰糖',
    itemVal15: 30,
    itemUnit15: null,
    itemName16: '香果',
    itemVal16: 30,
    itemUnit16: null,
    itemName17: '山奈',
    itemVal17: 40,
    itemUnit17: null,
    itemName18: '香砂仁',
    itemVal18: 40,
    itemUnit18: null,
    itemName19: '毕波',
    itemVal19: 16,
    itemUnit19: null,
    itemName20: '广木香',
    itemVal20: 12,
    itemUnit20: null,
    itemName21: '灵草',
    itemVal21: 20,
    itemUnit21: null,
    itemName22: '当归',
    itemVal22: 12,
    itemUnit22: null,
    itemName23: '甘松',
    itemVal23: 30,
    itemUnit23: null,
    itemName24: '栀子',
    itemVal24: 20,
    itemUnit24: null,
    itemName25: '辣椒',
    itemVal25: 60,
    itemUnit25: null,
    itemName26: '红花椒',
    itemVal26: 40,
    itemUnit26: null,
    keys: [],
    calcFactor: 1,
  },
  {
    title: '家用卤菜配方',
    remark: null,
    starLevel: 3,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '八角',
    itemVal1: 20,
    itemUnit1: null,
    itemName2: '桂皮',
    itemVal2: 12,
    itemUnit2: null,
    itemName3: '白芷',
    itemVal3: 8,
    itemUnit3: null,
    itemName4: '公丁香',
    itemVal4: 4,
    itemUnit4: null,
    itemName5: '荜拨',
    itemVal5: 5,
    itemUnit5: null,
    itemName6: '小茴香',
    itemVal6: 15,
    itemUnit6: null,
    itemName7: '香果(拍破)',
    itemVal7: 8,
    itemUnit7: null,
    itemName8: '罗汉果(拍破)',
    itemVal8: 20,
    itemUnit8: null,
    itemName9: '草果(拍破)',
    itemVal9: 10,
    itemUnit9: null,
    itemName10: '白豆蔻',
    itemVal10: 5,
    itemUnit10: null,
    itemName11: '栀子(拍破)',
    itemVal11: 5,
    itemUnit11: null,
    itemName12: '甘草',
    itemVal12: 8,
    itemUnit12: null,
    itemName13: '良姜',
    itemVal13: 6,
    itemUnit13: null,
    itemName14: '川砂仁(拍破)',
    itemVal14: 10,
    itemUnit14: null,
    itemName15: '山奈',
    itemVal15: 10,
    itemUnit15: null,
    itemName16: '干姜',
    itemVal16: 7,
    itemUnit16: null,
    itemName17: '陈皮',
    itemVal17: 3,
    itemUnit17: null,
    itemName18: '灵草',
    itemVal18: 2,
    itemUnit18: null,
    itemName19: '排草',
    itemVal19: 3,
    itemUnit19: null,
    itemName20: '胡椒',
    itemVal20: 10,
    itemUnit20: null,
    itemName21: '花椒',
    itemVal21: 25,
    itemUnit21: null,
    itemName22: '辣椒',
    itemVal22: 30,
    itemUnit22: null,
  },
];
console.log(`卤味、卤水配方共有${formulasFoodsListMarinade.length}个`);
