/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2024-07-12 11:50:38
 * @FilePath: /cooking-menu/src/views/more/formulasConversion/formulas.data.ts
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 主食-配方换算
 */
// import { lampshadedBeefScriptsList } from './riceFoodScriptContent/lampshadedBeef';
export const formulasFoodsList = [
  {
    title: '家用卤菜配方',
    starLevel: 5,
    itemName0: '主材',
    itemVal0: 500,
    itemUnit0: '克',
    itemName1: '八角',
    itemVal1: 4,
    itemUnit1: '颗',
    itemName2: '花椒',
    itemVal2: 40,
    itemUnit2: '粒',
    itemName3: '陈皮',
    itemVal3: 1,
    itemUnit3: '块',
    itemName4: '草果',
    itemVal4: 2,
    itemUnit4: '颗',
    itemName5: '桂皮',
    itemVal5: 1,
    itemUnit5: '根（约中指大小）',
    itemName6: '香叶',
    itemVal6: 2,
    itemUnit6: '片',
    itemName7: '干红辣椒',
    itemVal7: 3,
    itemUnit7: '根',
    itemName8: '料酒',
    itemVal8: 30,
    itemUnit8: 'ml（2汤匙）',
    itemName9: '生抽',
    itemVal9: 30,
    itemUnit9: 'ml（2汤匙）',
    itemName10: '老抽',
    itemVal10: 45,
    itemUnit10: 'ml（2汤匙）',
    itemName11: '白糖',
    itemVal11: 5,
    itemUnit11: '克(g/1茶匙)',
    itemName12: '冰糖',
    itemVal12: 30,
    itemUnit12: '克(g/1小把)',
    itemName13: '盐',
    itemVal13: 5,
    itemUnit13: '克(g/1茶匙)',
    keys: [],
    calcFactor: 1,
  },
  {
    title: '家用卤菜配方',
    starLevel: 3,
    itemName0: '主材',
    itemVal0: 500,
    itemUnit0: '克',
    itemName1: '姜',
    itemVal1: 1,
    itemUnit1: '块',
    itemName2: '大葱',
    itemVal2: 1,
    itemUnit2: '根',
    itemName3: '蒜',
    itemVal3: 3,
    itemUnit3: '瓣',
    itemName4: '草果',
    itemVal4: 2,
    itemUnit4: '颗',
    itemName5: '桂皮',
    itemVal5: 1,
    itemUnit5: '根（约中指大小）',
    itemName6: '香叶',
    itemVal6: 2,
    itemUnit6: '片',
    itemName7: '干红辣椒',
    itemVal7: 3,
    itemUnit7: '根',
    itemName8: '料酒',
    itemVal8: 30,
    itemUnit8: 'ml（2汤匙）',
    itemName9: '生抽',
    itemVal9: 30,
    itemUnit9: 'ml（2汤匙）',
    itemName10: '老抽',
    itemVal10: 45,
    itemUnit10: 'ml（2汤匙）',
    itemName11: '白糖',
    itemVal11: 5,
    itemUnit11: '克(g/1茶匙)',
    itemName12: '冰糖',
    itemVal12: 30,
    itemUnit12: '克(g/1小把)',
    itemName13: '盐',
    itemVal13: 5,
    itemUnit13: '克(g/1茶匙)',
    keys: [],
    calcFactor: 1,
  },
];
