/*
 * @Author: vigne 1186963387@qq.com
 * @Date: 2024-07-12 11:50:38
 * @FilePath: /cooking-menu/src/views/more/formulasConversion/formulasDipping.data.ts
 * @Description:
 *
 * Copyright (c) 2024 by ${git_name_email}, All Rights Reserved.
 */
/**
 * 主食-配方换算-蘸碟、蘸水、蘸料配方
 */

// import { lampshadedBeefScriptsList } from './riceFoodScriptContent/lampshadedBeef';
const ar = [
  '主材',
  '花椒',
  '胡椒掺合粉(1:1)',
  '醋',
  '酱油',
  '辣椒油',
  '蒜水各一勺',
  '白芝麻',
  '味精',
  '鸡精适量',
];
const list = {
  title: '',
  remark: null,
  starLevel: 1,
};
ar.map((item, i) => {
  list['itemName' + i] = item;
  list['itemVal' + i] = i;
  list['itemUnit' + i] = null;
});
console.log('蘸碟、蘸水、蘸料配方换算', list);
export const formulasFoodsListDipping = [
  {
    title: '五香粉',
    remark: null,
    starLevel: 1,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '花椒',
    itemVal1: 4,
    itemUnit1: null,
    itemName2: '八角',
    itemVal2: 4,
    itemUnit2: null,
    itemName3: '丁香',
    itemVal3: 1,
    itemUnit3: null,
    itemName4: '桂皮',
    itemVal4: 2,
    itemUnit4: null,
    itemName5: '小茴香',
    itemVal5: 2,
    itemUnit5: null,
  },
  {
    title: '椒盐粉',
    remark: null,
    starLevel: 1,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '花椒',
    itemVal1: 8,
    itemUnit1: null,
    itemName2: '小茴香',
    itemVal2: 6,
    itemUnit2: null,
    itemName3: '熟芝麻',
    itemVal3: 10,
    itemUnit3: null,
    itemName4: '盐',
    itemVal4: 10,
    itemUnit4: null,
    itemName5: '味精',
    itemVal5: 4,
    itemUnit5: null,
    itemName6: '鸡精',
    itemVal6: 3,
    itemUnit6: null,
    itemName7: '熟黄豆',
    itemVal7: 8,
    itemUnit7: null,
  },
  {
    title: '十三香',
    remark: null,
    starLevel: 1,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '小茴香',
    itemVal1: 20,
    itemUnit1: null,
    itemName2: '花椒',
    itemVal2: 11,
    itemUnit2: null,
    itemName3: '八角',
    itemVal3: 10,
    itemUnit3: null,
    itemName4: '肉桂',
    itemVal4: 10,
    itemUnit4: null,
    itemName5: '干姜',
    itemVal5: 8,
    itemUnit5: null,
    itemName6: '砂仁',
    itemVal6: 6,
    itemUnit6: null,
    itemName13: '肉蔻',
    itemVal13: 5,
    itemUnit13: null,
    itemName7: '丁香',
    itemVal7: 5,
    itemUnit7: null,
    itemName8: '良姜',
    itemVal8: 4,
    itemUnit8: null,
    itemName9: '陈皮',
    itemVal9: 4,
    itemUnit9: null,
    itemName10: '草蔻',
    itemVal10: 4,
    itemUnit10: null,
    itemName11: '木香',
    itemVal11: 3,
    itemUnit11: null,
    itemName12: '山奈',
    itemVal12: 3,
    itemUnit12: null,
  },
  {
    title: '干碟蘸料',
    remark: null,
    starLevel: 1,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '辣椒面',
    itemVal1: 10,
    itemUnit1: null,
    itemName2: '盐',
    itemVal2: 3,
    itemUnit2: null,
    itemName3: '味精',
    itemVal3: 2,
    itemUnit3: null,
    itemName4: '黄豆面',
    itemVal4: 2,
    itemUnit4: null,
    itemName5: '花生面',
    itemVal5: 2,
    itemUnit5: null,
    itemName6: '鸡精',
    itemVal6: 2,
    itemUnit6: null,
    itemName7: '熟芝麻',
    itemVal7: 2,
    itemUnit7: null,
  },
  {
    title: '椒麻蘸碟',
    remark: null,
    starLevel: 1,
    itemName0: '主材',
    itemVal0: 1,
    itemUnit0: null,
    itemName1: '红花椒',
    itemVal1: 10,
    itemUnit1: null,
    itemName2: '小葱,只要小葱绿',
    itemVal2: 30,
    itemUnit2: null,
    itemName3: '盐',
    itemVal3: 3,
    itemUnit3: null,
    itemName4: '白糖',
    itemVal4: 2,
    itemUnit4: null,
    itemName5: '味精',
    itemVal5: 2,
    itemUnit5: null,
    itemName6: '香油',
    itemVal6: null,
    itemUnit6: '少量',
    itemName7: '凉开水',
    itemVal7: null,
    itemUnit7: '少量',
  },
];
console.log(`蘸碟、蘸水、蘸料配方共有${formulasFoodsListDipping.length}个`);
